language: node.js
node_js:
  - 13

services:
  - docker

script:
  - docker --version 
  - docker build -t simple_node .
  - docker tag simple-node fr77/my-simple-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fr77/my-simple-node


